// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexopostal.Intranet.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexopostal.Intranet.Migrations
{
    [DbContext(typeof(IntranetDbContext))]
    [Migration("20260522183711_AddAsignacionOficinaCampos")]
    partial class AddAsignacionOficinaCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexopostal.Intranet.Models.AsignacionPaquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignadoPorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CtaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("boolean");

                    b.Property<int>("EstadoTarea")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroExpedicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OficinaJsonId")
                        .HasColumnType("integer");

                    b.Property<string>("OficinaNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OperarioAsignadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("OperarioOficinaAsignadoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoTarea")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoPorId");

                    b.HasIndex("EstadoTarea")
                        .HasDatabaseName("IX_AsignacionesPaquetes_EstadoTarea");

                    b.HasIndex("NumeroExpedicion")
                        .HasDatabaseName("IX_AsignacionesPaquetes_NumeroExpedicion");

                    b.HasIndex("CtaId", "EstadoTarea")
                        .HasDatabaseName("IX_AsignacionesPaquetes_Cta_Estado");

                    b.HasIndex("OficinaJsonId", "EstadoTarea")
                        .HasDatabaseName("IX_AsignacionesPaquetes_Oficina_Estado");

                    b.HasIndex("OperarioAsignadoId", "EstadoTarea")
                        .HasDatabaseName("IX_AsignacionesPaquetes_Operario_Estado");

                    b.HasIndex("OperarioOficinaAsignadoId", "EstadoTarea")
                        .HasDatabaseName("IX_AsignacionesPaquetes_OperarioOficina_Estado");

                    b.ToTable("AsignacionesPaquetes");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.CentroTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Area")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EsNodoAereo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsNodoMaritimo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Area")
                        .HasDatabaseName("IX_CentrosTratamiento_Area");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_CentrosTratamiento_Codigo");

                    b.ToTable("CentrosTratamiento");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoPrevio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroExpedicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroSeguimiento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("OperarioId")
                        .HasColumnType("integer");

                    b.Property<string>("OperarioNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TipoUbicacion")
                        .HasColumnType("integer");

                    b.Property<string>("UbicacionCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer");

                    b.Property<string>("UbicacionNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("VisibleParaCliente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FechaEvento")
                        .HasDatabaseName("IX_HistorialEstados_FechaEvento");

                    b.HasIndex("NumeroExpedicion")
                        .HasDatabaseName("IX_HistorialEstados_NumeroExpedicion");

                    b.HasIndex("NumeroSeguimiento")
                        .HasDatabaseName("IX_HistorialEstados_NumeroSeguimiento");

                    b.HasIndex("OperarioId");

                    b.HasIndex("NumeroExpedicion", "FechaEvento")
                        .HasDatabaseName("IX_HistorialEstados_Expedicion_Fecha");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CtaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroExpedicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ReportadaPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Resolucion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Incidencias_Estado");

                    b.HasIndex("NumeroExpedicion")
                        .HasDatabaseName("IX_Incidencias_NumeroExpedicion");

                    b.HasIndex("ReportadaPorId");

                    b.HasIndex("CtaId", "Estado")
                        .HasDatabaseName("IX_Incidencias_Cta_Estado");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.MovimientoPaquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CtaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("CtaOrigenId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroExpedicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TipoTransporte")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_MovimientosPaquetes_Estado");

                    b.HasIndex("NumeroExpedicion")
                        .HasDatabaseName("IX_MovimientosPaquetes_NumeroExpedicion");

                    b.HasIndex("CtaDestinoId", "Estado")
                        .HasDatabaseName("IX_MovimientosPaquetes_CtaDestino_Estado");

                    b.HasIndex("CtaOrigenId", "Estado")
                        .HasDatabaseName("IX_MovimientosPaquetes_CtaOrigen_Estado");

                    b.ToTable("MovimientosPaquetes");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.OperarioCta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CentroTratamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroTratamientoId")
                        .HasDatabaseName("IX_OperariosCta_CentroTratamientoId");

                    b.HasIndex("CodigoEmpleado")
                        .HasDatabaseName("IX_OperariosCta_CodigoEmpleado");

                    b.HasIndex("IdentityUserId")
                        .HasDatabaseName("IX_OperariosCta_IdentityUserId");

                    b.HasIndex("IdentityUserId", "CentroTratamientoId")
                        .IsUnique()
                        .HasDatabaseName("IX_OperariosCta_Identity_Cta");

                    b.ToTable("OperariosCta");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.OperarioOficina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OficinaJsonId")
                        .HasColumnType("integer");

                    b.Property<string>("OficinaNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .HasDatabaseName("IX_OperariosOficina_IdentityUserId");

                    b.HasIndex("OficinaJsonId")
                        .HasDatabaseName("IX_OperariosOficina_OficinaJsonId");

                    b.HasIndex("IdentityUserId", "OficinaJsonId")
                        .IsUnique()
                        .HasDatabaseName("IX_OperariosOficina_Identity_Oficina");

                    b.ToTable("OperariosOficina");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.RutaCta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CtaId")
                        .HasColumnType("integer");

                    b.Property<string>("PrefijoCp")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CtaId");

                    b.HasIndex("PrefijoCp")
                        .IsUnique()
                        .HasDatabaseName("IX_RutasCta_PrefijoCp");

                    b.ToTable("RutasCta");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.AsignacionPaquete", b =>
                {
                    b.HasOne("Nexopostal.Intranet.Models.OperarioCta", "AsignadoPor")
                        .WithMany("AsignacionesCreadas")
                        .HasForeignKey("AsignadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexopostal.Intranet.Models.CentroTratamiento", "Cta")
                        .WithMany("Asignaciones")
                        .HasForeignKey("CtaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexopostal.Intranet.Models.OperarioCta", "OperarioAsignado")
                        .WithMany("AsignacionesRecibidas")
                        .HasForeignKey("OperarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexopostal.Intranet.Models.OperarioOficina", "OperarioOficinaAsignado")
                        .WithMany()
                        .HasForeignKey("OperarioOficinaAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsignadoPor");

                    b.Navigation("Cta");

                    b.Navigation("OperarioAsignado");

                    b.Navigation("OperarioOficinaAsignado");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.HistorialEstado", b =>
                {
                    b.HasOne("Nexopostal.Intranet.Models.OperarioCta", "Operario")
                        .WithMany()
                        .HasForeignKey("OperarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Operario");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.Incidencia", b =>
                {
                    b.HasOne("Nexopostal.Intranet.Models.CentroTratamiento", "Cta")
                        .WithMany("Incidencias")
                        .HasForeignKey("CtaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexopostal.Intranet.Models.OperarioCta", "ReportadaPor")
                        .WithMany("IncidenciasReportadas")
                        .HasForeignKey("ReportadaPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cta");

                    b.Navigation("ReportadaPor");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.MovimientoPaquete", b =>
                {
                    b.HasOne("Nexopostal.Intranet.Models.CentroTratamiento", "CtaDestino")
                        .WithMany("MovimientosDestino")
                        .HasForeignKey("CtaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexopostal.Intranet.Models.CentroTratamiento", "CtaOrigen")
                        .WithMany("MovimientosOrigen")
                        .HasForeignKey("CtaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CtaDestino");

                    b.Navigation("CtaOrigen");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.OperarioCta", b =>
                {
                    b.HasOne("Nexopostal.Intranet.Models.CentroTratamiento", "CentroTratamiento")
                        .WithMany("Operarios")
                        .HasForeignKey("CentroTratamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroTratamiento");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.RutaCta", b =>
                {
                    b.HasOne("Nexopostal.Intranet.Models.CentroTratamiento", "Cta")
                        .WithMany("RutasAsignadas")
                        .HasForeignKey("CtaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cta");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.CentroTratamiento", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Incidencias");

                    b.Navigation("MovimientosDestino");

                    b.Navigation("MovimientosOrigen");

                    b.Navigation("Operarios");

                    b.Navigation("RutasAsignadas");
                });

            modelBuilder.Entity("Nexopostal.Intranet.Models.OperarioCta", b =>
                {
                    b.Navigation("AsignacionesCreadas");

                    b.Navigation("AsignacionesRecibidas");

                    b.Navigation("IncidenciasReportadas");
                });
#pragma warning restore 612, 618
        }
    }
}
