// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexopostal.Reparto.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexopostal.Reparto.Migrations
{
    [DbContext(typeof(RepartoDbContext))]
    [Migration("20260521220436_AddVehiculos")]
    partial class AddVehiculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexopostal.Reparto.Models.EntregaPaquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaIntento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaDigital")
                        .HasColumnType("text");

                    b.Property<string>("FotoEntrega")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("LatitudEntrega")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongitudEntrega")
                        .HasColumnType("double precision");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroExpedicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NumeroIntento")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroSeguimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrdenEnRuta")
                        .HasColumnType("integer");

                    b.Property<string>("ReceptorDni")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ReceptorNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RutaRepartoId")
                        .HasColumnType("integer");

                    b.Property<string>("TelefonoDestinatario")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_EntregasPaquetes_Estado");

                    b.HasIndex("NumeroExpedicion")
                        .HasDatabaseName("IX_EntregasPaquetes_NumeroExpedicion");

                    b.HasIndex("NumeroSeguimiento")
                        .HasDatabaseName("IX_EntregasPaquetes_NumeroSeguimiento");

                    b.HasIndex("RutaRepartoId", "OrdenEnRuta")
                        .HasDatabaseName("IX_EntregasPaquetes_Ruta_Orden");

                    b.ToTable("EntregasPaquetes");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.Repartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("MatriculaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OficinaJsonId")
                        .HasColumnType("integer");

                    b.Property<string>("OficinaNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique()
                        .HasDatabaseName("IX_Repartidores_CodigoEmpleado");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Repartidores_IdentityUserId");

                    b.HasIndex("OficinaJsonId")
                        .HasDatabaseName("IX_Repartidores_OficinaJsonId");

                    b.ToTable("Repartidores");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.RutaReparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaReparto")
                        .HasColumnType("date");

                    b.Property<DateTime?>("HoraRegreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OficinaOrigenJsonId")
                        .HasColumnType("integer");

                    b.Property<string>("OficinaOrigenNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_RutasReparto_Codigo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_RutasReparto_Estado");

                    b.HasIndex("FechaReparto")
                        .HasDatabaseName("IX_RutasReparto_FechaReparto");

                    b.HasIndex("RepartidorId", "FechaReparto")
                        .HasDatabaseName("IX_RutasReparto_Repartidor_Fecha");

                    b.ToTable("RutasReparto");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.UbicacionRepartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<int?>("RutaActivaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId")
                        .IsUnique()
                        .HasDatabaseName("IX_UbicacionesRepartidores_RepartidorId");

                    b.ToTable("UbicacionesRepartidores");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("AnioFabricacion")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ModificadoPorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OficinaJsonId")
                        .HasColumnType("integer");

                    b.Property<int?>("RepartidorAsignadoId")
                        .HasColumnType("integer");

                    b.Property<string>("RepartidorAsignadoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Vehiculos_Activo");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("IX_Vehiculos_Matricula");

                    b.HasIndex("OficinaJsonId")
                        .HasDatabaseName("IX_Vehiculos_OficinaJsonId");

                    b.HasIndex("RepartidorAsignadoId")
                        .HasDatabaseName("IX_Vehiculos_RepartidorAsignadoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.EntregaPaquete", b =>
                {
                    b.HasOne("Nexopostal.Reparto.Models.RutaReparto", "RutaReparto")
                        .WithMany("Entregas")
                        .HasForeignKey("RutaRepartoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RutaReparto");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.RutaReparto", b =>
                {
                    b.HasOne("Nexopostal.Reparto.Models.Repartidor", "Repartidor")
                        .WithMany("Rutas")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.UbicacionRepartidor", b =>
                {
                    b.HasOne("Nexopostal.Reparto.Models.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.Repartidor", b =>
                {
                    b.Navigation("Rutas");
                });

            modelBuilder.Entity("Nexopostal.Reparto.Models.RutaReparto", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
